#=========================================================================
# Cadence Innovus Place and Route
#=========================================================================
# Author : Christopher Torng
# Date   : June 7, 2019
#

name: cadence-innovus-place-route

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - innovus-foundation-flow
  - adk
  - design.v
  - design.sdc

outputs:
  - design.checkpoint
  - design.gds.gz
  - design.lvs.v
  - design.vcs.v
  - design.lef
  - design.pt.sdc
  - design.sdf
  - design.virtuoso.v
  - design.spef.gz

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - ln -sf inputs/innovus-foundation-flow
  - innovus -overwrite -64 -nowin -init START.tcl -log logs/run.log

  # Outputs
  - cd outputs
  - ln -sf ../checkpoints/design.checkpoint
  - ln -sf ../typical.spef.gz      design.spef.gz
  - ln -sf ../results/*.gds.gz     design.gds.gz
  - ln -sf ../results/*.lvs.v      design.lvs.v
  - ln -sf ../results/*.vcs.v      design.vcs.v
  - ln -sf ../results/*.lef        design.lef
  - ln -sf ../results/*.pt.sdc     design.pt.sdc
  - ln -sf ../results/*.sdf        design.sdf
  - ln -sf ../results/*.virtuoso.v design.virtuoso.v

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  order:
    - init/main.tcl
    - init/quality-of-life.tcl
    - init/floorplan.tcl
    - init/add-endcaps-welltaps.tcl
    - init/pin-assignments.tcl
    - init/make-path-groups.tcl
    - init/reporting.tcl
    - power/globalnetconnect.tcl
    - power/main.tcl
    - place/setup-cellpad.tcl
    - place/main.tcl
    - place/clean-cellpad.tcl
    - place/reporting.tcl
    - cts/setup-ccopt.tcl
    - cts/main.tcl
    - cts/reporting.tcl
    - postcts_hold/setup-optmode.tcl
    - postcts_hold/main.tcl
    - route/main.tcl
    - postroute/setup-optmode.tcl
    - postroute/main.tcl
    - postroute_hold/main.tcl
    - signoff/main.tcl
    - signoff/generate-results.tcl
    - signoff/reporting.tcl

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - innovus -overwrite -64
    -init innovus-foundation-flow/custom-scripts/run-debug.tcl
    -log logs/debug.log

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'innovus' )                         # tool check
  - assert File( 'inputs/innovus-foundation-flow' )  # must exist
  - assert File( 'inputs/adk' )                      # must exist
  - assert File( 'inputs/design.sdc' )               # must exist

postconditions:

  - assert File( 'outputs/design.checkpoint' )       # must exist


