#=========================================================================
# Synopsys DC Synthesis
#=========================================================================
# Author : Christopher Torng
# Date   : June 7, 2019
#

name: synopsys-dc-synthesis

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.v

outputs:
  - design.v
  - design.sdc

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - bash run.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 1.0
  design_name: undefined

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - export DC_EXIT_AFTER_SETUP=1
  - ln -sf results/*.mapped.ddc debug.ddc
  - python dump-parameters.py
  - source ./params.sh
  - design_vision-xg -topographical -x "source dc.tcl; read_ddc debug.ddc"

